algorithm = 'jumpteaching'
dataset = 'webvision'
input_channel = 3
num_classes = 50           
root = '/path/to/Webvision/'  # Update to your WebVision dataset path
imgnet_root = '/path/to/imagenet'  # Update to your ImageNet dataset path
noise_type = 'real'        
percent = 0.0              
seed = 1
loss_type = 'ce'
model1_type = 'InceptionResNetV2SH'
model2_type = 'none'
gpu = '1'                  
batch_size = 32            
epochs = 100
num_workers = 4
epoch_decay_start = 30
alpha = 5.0
hashbits = 64
tau = 0.001
T = 2
Step = 2
save_result = True
labelhashcodes_path = './labels/'
